version: '3.8'
services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0  # Use the official MySQL image
    container_name: mysql_db  # Name of the container
    environment:
      MYSQL_ROOT_PASSWORD: rocksprince123  # Root password for MySQL
      MYSQL_DATABASE: erms-db  # Name of the database to create
      MYSQL_USER: appuser  # MySQL username
      MYSQL_PASSWORD: rocksprince123  # MySQL password
    ports:
      - "3307:3306"  # Expose MySQL port to the host
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data in a volume

  # Spring Boot Backend Service
  backendapp:
    image: dbomar123/backendapp:latest  # Your Spring Boot Docker image
    container_name: backend_app
    ports:
      - "8080:8080"  # Expose Spring Boot port to the host
    depends_on:
      - mysql  # Ensure MySQL starts before Spring Boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/erms-db  # JDBC URL for MySQL
      SPRING_DATASOURCE_USERNAME: appuser  # MySQL username
      SPRING_DATASOURCE_PASSWORD: rocksprince123  # MySQL password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Hibernate property
      SPRING_JPA_SHOW_SQL: true  # Hibernate property
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver  # JDBC driver class
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10  # Hikari pool size
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 5  # Hikari minimum idle connections


volumes:
  mysql_data: